   repos:
     - repo: https://github.com/psf/black
       rev: 23.1.0  # Use the latest stable version or specify a version
       hooks:
         - id: black
           language_version: python3

     - repo: https://github.com/nbQA-dev/nbQA
       rev: 1.5.0  # Use the latest stable version or specify a version
       hooks:
         - id: nbqa-black
           args: ["--line-length=88"]  # Optional: specify any Black arguments